<wsdl:definitions targetNamespace="http://xmlns.oracle.com/pcbpel/adapter/db/BRIEF-24006/HITTS_GetSegmByDocument/GetSegmByDocument_BS" name="GetSegmByDocument_BS-concrete" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/">
    <wsdl:import location="../WSDLs/GetSegmByDocument_BD.wsdl" namespace="http://xmlns.oracle.com/pcbpel/adapter/db/BRIEF-24006/HITTS_GetSegmByDocument/GetSegmByDocument_BS"/>
    <wsdl:binding name="GetSegmByDocument_BS_ptt-binding" type="get:GetSegmByDocument_BS_ptt" xmlns:get="http://xmlns.oracle.com/pcbpel/adapter/db/BRIEF-24006/HITTS_GetSegmByDocument/GetSegmByDocument_BS">
        <soap:binding style="document" transport="http://www.bea.com/wli/sb/transports/jca"/>
        <wsdl:operation name="GetSegmByDocument_BS">
            <soap:operation soapAction="GetSegmByDocument_BS"/>
            <wsdl:input>
                <soap:body use="literal"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>