<?xml version= '1.0' encoding= 'UTF-8' ?>
<wsdl:definitions
     name="GetSegmByDocument_PS"
     targetNamespace="http://xmlns.oracle.com/BRIEF-24006/HITTS_GetSegmByDocument/GetSegmByDocument_PS"
     xmlns:tns="http://xmlns.oracle.com/BRIEF-24006/HITTS_GetSegmByDocument/GetSegmByDocument_PS"
     xmlns:inp1="http://www.example.org"
     xmlns:xsd="http://www.w3.org/2001/XMLSchema"
     xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
     xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    >
    <wsdl:types>
        <xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
            <xsd:import namespace="http://www.example.org" schemaLocation="../Schemas/GetSegmByDocument_PS.xsd"/>
        </xsd:schema>
    </wsdl:types>
    <wsdl:message name="requestMessage">
        <wsdl:part name="Input" element="inp1:GetSegmByDocumentRequestPS"/>
    </wsdl:message>
    <wsdl:message name="replyMessage">
        <wsdl:part name="Output" element="inp1:GetSegmByDocumentResponsivePS"/>
    </wsdl:message>
    <wsdl:portType name="execute_ptt">
        <wsdl:operation name="GetSegmByDocument_PS">
            <wsdl:input message="tns:requestMessage"/>
            <wsdl:output message="tns:replyMessage"/>
        </wsdl:operation>
    </wsdl:portType>
    <wsdl:binding name="execute_bind" type="tns:execute_ptt">
        <soap:binding transport="http://schemas.xmlsoap.org/soap/http"/>
        <wsdl:operation name="GetSegmByDocument_PS">
            <soap:operation style="document" soapAction="GetSegmByDocument_PS"/>
            <wsdl:input>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/BRIEF-24006/HITTS_GetSegmByDocument/GetSegmByDocument_PS"/>
            </wsdl:input>
            <wsdl:output>
                <soap:body use="literal" namespace="http://xmlns.oracle.com/BRIEF-24006/HITTS_GetSegmByDocument/GetSegmByDocument_PS"/>
            </wsdl:output>
        </wsdl:operation>
    </wsdl:binding>
</wsdl:definitions>
